import turtle
text = turtle.textinput("заголовок", "введите текст")
turtle.write(text, font =('Arial', 12, 'normal'))
turtle.fillcolor('red')
turtle.begin_fill()
turtle.pensize(5) 
turtle.circle(50)
turtle.end_fill()
turtle.left(180)
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.pensize(5) 
turtle.circle(50)
turtle.end_fill()
turtle.penup() 
turtle.goto(0,-100)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.pensize(5) 
turtle.circle(50)
turtle.end_fill()
